spring:
  main:
    banner-mode: 'off'
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss

logging:
  level:
    es.bvalero.replacer: INFO
    org.hibernate: ERROR
    org.springframework: ERROR

replacer:
  # Path where the XML dumps are located for the Spanish Wikipedia
  dump.folder.path: /public/dumps/public/eswiki
  highlight.exceptions: false
  hide.empty.paragraphs: true
  trim.paragraphs: true

wikipedia:
  username: BenjaBot
  # Externalized
  password: xxxxxx

---

spring:
  profiles: offline
  datasource:
    platform: h2

logging:
  level:
    es.bvalero.replacer: DEBUG
    org.hibernate.SQL: DEBUG

replacer:
  # Path where the XML dumps are located for the Spanish Wikipedia
  dump.folder.path: C:\Users\Benja\Desarrollo\pywikibot

---

spring:
  profiles: default
  datasource:
    url: jdbc:mariadb://tools-db:3306/s52978__replacer
    username: s52978
    # Externalized
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  # Rolling after 10M after the documentation
  file: logs/replacer.log
