spring:
  main:
    banner-mode: 'off'
  output:
    ansi.enabled: ALWAYS
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  profiles.include: @includeSpringProfile@

server:
  port: 8080 # Default port for local deployment
  compression.enabled: true

replacer:
  cors.allowed.origins: http://localhost:8080
  dump:
    path.base: /Users/benja/Developer
    batch:
      delay: 604800000 # Weekly
      delay.initial: 86400000 # 1 day
      chunk.size: 5000
  parse.file.delay: 3600000 # Every hour
  wikipedia.api:
    key: 88a04ea6ad93434f0fff31ac434960b3
    secret: 2e2bfb55301e030aa6bf8c2504624abdd12f2d04
  page.stats.delay: 300000 # Every 5 minutes
  show.immutable.warning: true
  admin.user: Benjavalero
  indexable.namespaces: 0,104

---

# Profile for Production
spring:
  profiles: default
  datasource:
    url: jdbc:mariadb://tools-db:3306/s52978__replacer?rewriteBatchedStatements=true
    username: s52978
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver
    hikari.max-lifetime: 580000

server:
  port: 8000

replacer:
  dump:
    path.base: /public/dumps/public
    # Externalized to be tweaked easily. Higher values throw heap overflows.
    batch.chunk.size: 500
  wikipedia.api:
    key: xxxxxx
    secret: xxxxxx

---

spring:
  profiles: backend

server:
  # Port to deploy only the backend and use the frontend deployed independently
  port: 8000

---

# Local access to production database via SSH tunnel
spring:
  profiles: db-prod
  datasource:
    url: jdbc:mariadb://localhost:3306/s52978__replacer?rewriteBatchedStatements=true
    username: s52978
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver
    hikari.max-lifetime: 580000

---

# Local persistent database
spring:
  profiles: db-local
  datasource:
    url: jdbc:h2:./replacer-h2;MODE=MySQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: never # Set to "always" the first time

replacer.page.stats.delay: 600000 # Every 10 minutes

---

# Local in-memory database and mocked calls to Wikipedia API
spring:
  profiles: offline
  datasource:
    platform: h2

replacer.admin.user: offline
