spring:
  main:
    banner-mode: 'off'
  output:
    ansi.enabled: ALWAYS
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  batch:
    job.enabled: false
    initialize-schema: always
    initializer.enabled: true

server:
  port: 8000
  # For SpringBoot 1.x the property is server.context-path
  servlet.context-path: /replacer/
  compression.enabled: true

logging:
  level:
    es.bvalero.replacer: INFO
    org.hibernate: ERROR
    org.springframework: ERROR
    org.springframework.batch: INFO

replacer:
  dump:
    path:
      base: /public/dumps/public
      project: eswiki
    batch:
      delay: 604800000 # Weekly
      delay.initial: 86400000 # 1 day
      chunk.size: 10000

  admin.user: Benjavalero
  parse.file.delay: 3600000 # Every hour
  article.stats.delay: 600000 # Every 10 minutes

wikipedia:
  api:
    # Externalized
    key: 88a04ea6ad93434f0fff31ac434960b3
    secret: 2e2bfb55301e030aa6bf8c2504624abdd12f2d04

---

spring:
  profiles: offline
  datasource:
    platform: h2

replacer:
  dump.path:
    base: /Users/benja/Developer

---

spring:
  profiles: default
  # Externalized
  datasource:
    url: jdbc:mariadb://localhost:3306/s52978__replacer?rewriteBatchedStatements=true
    username: s52978
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver
    hikari.max-lifetime: 580000

logging:
  # Rolling after 10M after the documentation
  file: logs/replacer.log
  # Disable console logging
  pattern.console:
