spring:
  main:
    banner-mode: 'off'
  output:
    ansi.enabled: ALWAYS
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  batch.job.enabled: false

server:
  port: 8000
  # For SpringBoot 1.x the property is server.context-path
  servlet.context-path: /replacer/
  compression.enabled: true

logging:
  level:
    es.bvalero.replacer: INFO
    org.hibernate: ERROR
    org.springframework: ERROR

replacer:
  dump.path:
    base: /public/dumps/public
    project: eswiki

  admin.user: Benjavalero
  parse.file.delay: 3600000 # Every hour
  dump.index.delay: 86400000 # Daily
  article.stats.delay: 600000 # Every 10 minutes
  dump.index.wait: 3 # Days to wait after a dump is generated

wikipedia:
  api:
    # Externalized
    key: 88a04ea6ad93434f0fff31ac434960b3
    secret: 2e2bfb55301e030aa6bf8c2504624abdd12f2d04

---

spring:
  profiles: offline
  datasource:
    platform: h2

replacer:
  dump.path:
    base: /Users/benja/Developer

---

spring:
  profiles: batch
  datasource:
    initialization-mode: always # Only for tests to reset the database !!!
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/s52978__replacer?rewriteBatchedStatements=true
    username: s52978
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    initialize-schema: always
    initializer.enabled: true

logging:
  level:
    org.springframework: INFO

input.file: classpath:replacements-cut.csv
chunk.size: 1000

---

spring:
  profiles: default
  # Externalized
  datasource:
    url: jdbc:mariadb://localhost:3306/s52978__replacer
    username: s52978
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  # Rolling after 10M after the documentation
  file: logs/replacer.log
  # Disable console logging
  pattern.console:
