spring:
  main:
    banner-mode: 'off'
  output:
    ansi.enabled: ALWAYS
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss

server:
  port: 8000
  # For SpringBoot 1.x the property is server.context-path
  servlet.context-path: /replacer/

logging:
  level:
    es.bvalero.replacer: INFO
    org.hibernate: ERROR
    org.springframework: ERROR

replacer:
  # Path where the XML dumps are located for the Spanish Wikipedia
  dump.folder.path: /public/dumps/public/eswiki
  # Hide paragraphs not containing potential replacements and trim the ones matching
  hide.empty.paragraphs: true

wikipedia:
  # TODO Externalize
  api:
    key: 88a04ea6ad93434f0fff31ac434960b3
    secret: 2e2bfb55301e030aa6bf8c2504624abdd12f2d04

---

spring:
  profiles: offline
  datasource:
    platform: h2

replacer:
  dump.folder.path: /Users/benja/Developer/pywikibot

---

spring:
  profiles: default
  datasource:
    url: jdbc:mariadb://tools-db:3306/s52978__replacer
    username: s52978
    # Externalized
    password: xxxxxx
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  # Rolling after 10M after the documentation
  file: logs/replacer.log
