CREATE TABLE IF NOT EXISTS replacement (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CONTEXT VARCHAR(255),
	LANG VARCHAR(2),
	LAST_UPDATE DATE NOT NULL,
	ARTICLE_ID INTEGER,
	"POSITION" INTEGER DEFAULT 0,
	REVIEWER VARCHAR(100),
	SUBTYPE VARCHAR(100) NOT NULL,
	TITLE VARCHAR(255),
	"TYPE" VARCHAR(25) NOT NULL,
	CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS idx_count ON replacement (lang, reviewer, type, subtype);
CREATE INDEX IF NOT EXISTS idx_count_no_type ON replacement (lang, reviewer);
CREATE INDEX IF NOT EXISTS idx_reviewer ON replacement (reviewer);
CREATE INDEX IF NOT EXISTS idx_dump ON replacement (lang, article_id, reviewer);
