CREATE TABLE IF NOT EXISTS REPLACEMENT2 (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CONTEXT VARCHAR(255),
	LANG VARCHAR(2),
	LAST_UPDATE DATE NOT NULL,
	ARTICLE_ID INTEGER,
	"POSITION" INTEGER DEFAULT 0,
	REVIEWER VARCHAR(255),
	SUBTYPE VARCHAR(30) NOT NULL,
	TITLE VARCHAR(255),
	"TYPE" VARCHAR(25) NOT NULL,
	CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS idx_count ON replacement2 (lang, reviewer, type, subtype);
CREATE INDEX IF NOT EXISTS idx_count_no_type ON replacement2 (lang, reviewer);
CREATE INDEX IF NOT EXISTS idx_reviewer ON replacement2 (reviewer);
CREATE INDEX IF NOT EXISTS idx_dump ON replacement2 (lang, article_id, reviewer);
